
.PHONY: target1

### Section 1
target1: ## Target 1
	@echo target1
	@exit 0

target22: ## Target 2
	@echo target22
	@exit 0

### Section 2
target333: ## Target 3
	@echo target333
	@exit 0

target4444: ## Target 4
	@echo target4444
	@exit 0