name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Tests
    runs-on: ubuntu-latest
    steps:

    - name: Set up go cache
      uses: actions/cache@v1
      with:
        path: ~/go
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
    
    - name: Set up vendor cache
      uses: actions/cache@v1
      with:
        path: vendor
        key: $${{ runner.os }}-vendor-${{ hashFiles('**/go.sum') }}
    
    - name: Set up dist cache
      uses: actions/cache@v1
      with:
        path: dist
        key: $${{ runner.os }}-dist-${{ hashFiles('dist/checksums.txt') }}

    - name: Set up Go 1.14.x
      uses: actions/setup-go@v1
      with:
        go-version: 1.14.x
      id: go

    - name: Git checkout
      uses: actions/checkout@v2
    
    - name: Dependencies
      run: |
        export PATH=$(go env GOPATH)/bin:$PATH
        # Run make depsdev if $(GOPATH)/bin directory is older then 24 hours
        ((find $(go env GOPATH)/bin -maxdepth 0 -ctime +1 | grep . > /dev/null 2> /dev/null || !test -d $(go env GOPATH)/bin) && (make depsdev; touch $(go env GOPATH)/bin)) || true
        make deps
    
    - name: Unit tests / Code coverage / Code complexity
      run: |
        export PATH=$(go env GOPATH)/bin:$PATH
        git config --global user.email "noreply@github.com"
        git config --global user.name "Unit Testing"
        make test
