on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*.*.*'
  
name: Create Release

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:

      - name: Set up go cache
        uses: actions/cache@v1
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-gobin-${{ hashFiles('**/go.sum') }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Set up Go 1.16.x
        uses: actions/setup-go@v1
        with:
          go-version: 1.16.x
      
      - name: Dependencies
        run: |
          export PATH=$(go env GOPATH)/bin:$PATH
          make depsdev
          git checkout go.mod go.sum

      - name: Run GoReleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export PATH=$(go env GOPATH)/bin:$PATH
          make release_github

